import io
import logging
import os
import threading
from http.server import BaseHTTPRequestHandler, HTTPServer
import fitz  # PyMuPDF
from fpdf import FPDF
from pptx import Presentation
from telegram import Update
from telegram.ext import (
    ApplicationBuilder,
    CommandHandler,
    ContextTypes,
    MessageHandler,
    filters,
)

# -------------------------------------------------------------
# CONFIGURATION & BRANDING
# -------------------------------------------------------------
BRAND_NAME = "Yash PPT Converter Bot"
BOT_TOKEN = os.environ.get("BOT_TOKEN", "YOUR_TELEGRAM_BOT_TOKEN_HERE")
PORT = int(os.environ.get("PORT", 8080))

logging.basicConfig(
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)
logger = logging.getLogger(__name__)


# -------------------------------------------------------------
# DUMMY WEB SERVER (Keeps Render Web Service alive)
# -------------------------------------------------------------
class HealthCheckHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/plain")
        self.end_headers()
        self.wfile.write(f"{BRAND_NAME} is alive and running!".encode("utf-8"))

    def log_message(self, format, *args):
        # Suppress standard HTTP request logging to keep console clean
        return


def run_dummy_server():
    server = HTTPServer(("0.0.0.0", PORT), HealthCheckHandler)
    logger.info(f"Dummy health check server running on port {PORT}")
    server.serve_forever()


# -------------------------------------------------------------
# EXTRACTION LOGIC (PPTX & PDF)
# -------------------------------------------------------------
def extract_from_pptx(file_bytes):
    """Extracts titles, text, and speaker notes from PPTX."""
    prs = Presentation(io.BytesIO(file_bytes))
    slides_data = []

    for idx, slide in enumerate(prs.slides, start=1):
        # Title extraction
        title = ""
        if slide.shapes.title and slide.shapes.title.text:
            title = slide.shapes.title.text.strip()
        else:
            title = f"Topic / Slide {idx}"

        # Body text extraction
        content = []
        for shape in slide.shapes:
            if shape.has_text_frame and shape != slide.shapes.title:
                for paragraph in shape.text_frame.paragraphs:
                    text = paragraph.text.strip()
                    if text and text not in content:
                        content.append(text)

        # Presenter Notes extraction
        notes = ""
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame:
            notes = slide.notes_slide.notes_text_frame.text.strip()

        slides_data.append({
            "num": idx,
            "title": title,
            "content": content,
            "notes": notes,
        })
    return slides_data


def extract_from_pdf(file_bytes):
    """Extracts text lines from PDF presentation slides."""
    doc = fitz.open(stream=file_bytes, filetype="pdf")
    slides_data = []

    for idx, page in enumerate(doc, start=1):
        text = page.get_text("text").strip()
        lines = [line.strip() for line in text.split("\n") if line.strip()]

        title = lines[0] if lines else f"Page {idx}"
        content = lines[1:] if len(lines) > 1 else []

        slides_data.append({
            "num": idx,
            "title": title,
            "content": content,
            "notes": "",
        })
    return slides_data


# -------------------------------------------------------------
# B&W PDF GENERATION
# -------------------------------------------------------------
class BWNotesPDF(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, f"Study Notes • {BRAND_NAME}", border=0, align="R")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by {BRAND_NAME}", align="C")


def create_bw_notes_pdf(slides_data):
    """Generates a clean black & white A4 printable PDF."""
    pdf = BWNotesPDF(orientation="P", unit="mm", format="A4")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    for item in slides_data:
        # Subtle horizontal divider
        pdf.set_draw_color(210, 210, 210)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)

        # Slide Number & Title
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(0, 0, 0)
        title_text = f"[{item['num']}] {item['title']}".encode("latin-1", "replace").decode("latin-1")
        pdf.multi_cell(0, 6, title_text)
        pdf.ln(2)

        # Bullet Points
        if item["content"]:
            pdf.set_font("Helvetica", "", 10)
            pdf.set_text_color(30, 30, 30)
            for bullet in item["content"]:
                clean_bullet = f"• {bullet}".encode("latin-1", "replace").decode("latin-1")
                pdf.multi_cell(0, 5.5, clean_bullet)
            pdf.ln(2)

        # Speaker / Presenter Notes
        if item["notes"]:
            pdf.set_font("Helvetica", "I", 9)
            pdf.set_text_color(70, 70, 70)
            notes_text = f"Speaker Notes: {item['notes']}".encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 5, notes_text)
            pdf.ln(2)

        pdf.ln(4)

    return bytes(pdf.output())


# -------------------------------------------------------------
# TELEGRAM HANDLERS
# -------------------------------------------------------------
async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Welcome message with brand name."""
    welcome_text = (
        f"👋 **Welcome to {BRAND_NAME}!**\n\n"
        "📄 Send me any **PPTX** or **PDF presentation**, and I will instantly convert it into a "
        "**clean, ink-saving Black & White study notes PDF**!\n\n"
        "✨ **What I do:**\n"
        "• Strips all heavy images & dark backgrounds\n"
        "• Extracts slide text, bullet points & presenter notes\n"
        "• Formats everything into neat, printable A4 pages\n\n"
        "🚀 **Just upload your file here to get started!**"
    )
    await update.message.reply_text(welcome_text, parse_mode="Markdown")


async def handle_document(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Processes uploaded PPTX/PDF and returns the notes PDF."""
    document = update.message.document
    file_name = document.file_name or "presentation"
    file_ext = file_name.split(".")[-1].lower()

    if file_ext not in ["pptx", "pdf"]:
        await update.message.reply_text(
            "⚠️ Please upload a valid **.pptx** or **.pdf** slide file.",
            parse_mode="Markdown",
        )
        return

    status_msg = await update.message.reply_text(
        "⏳ **Downloading and converting into B&W study notes... Please wait.**",
        parse_mode="Markdown",
    )

    try:
        # Download the file from Telegram into memory
        tg_file = await context.bot.get_file(document.file_id)
        file_bytes = await tg_file.download_as_bytearray()

        # Extract content
        if file_ext == "pptx":
            slides_data = extract_from_pptx(file_bytes)
        else:
            slides_data = extract_from_pdf(file_bytes)

        if not slides_data:
            await status_msg.edit_text("❌ Could not extract any readable text from this file.")
            return

        # Generate clean PDF
        output_pdf_bytes = create_bw_notes_pdf(slides_data)

        # Brand the output filename
        base_name = os.path.splitext(file_name)[0]
        output_filename = f"{base_name}_Yash_PPT_Converter_Bot.pdf"

        # Send back to user
        await update.message.reply_document(
            document=io.BytesIO(output_pdf_bytes),
            filename=output_filename,
            caption=f"✅ **Converted successfully by {BRAND_NAME}!**\n📄 Clean Black & White Study Notes.",
            parse_mode="Markdown",
        )
        await status_msg.delete()

    except Exception as e:
        logger.error(f"Error during conversion: {e}", exc_info=True)
        await status_msg.edit_text("❌ An error occurred during conversion. Please make sure the file is not password-protected.")


# -------------------------------------------------------------
# MAIN APPLICATION
# -------------------------------------------------------------
def main():
    # 1. Start the dummy HTTP server in a separate background thread for Render
    server_thread = threading.Thread(target=run_dummy_server, daemon=True)
    server_thread.start()

    # 2. Start the Telegram Bot
    if BOT_TOKEN == "YOUR_TELEGRAM_BOT_TOKEN_HERE" or not BOT_TOKEN:
        print("ERROR: BOT_TOKEN is missing! Please set your environment variable or edit main.py.")
        return

    app = ApplicationBuilder().token(BOT_TOKEN).build()

    app.add_handler(CommandHandler("start", start_command))
    app.add_handler(CommandHandler("help", start_command))
    app.add_handler(MessageHandler(filters.Document.ALL, handle_document))

    logger.info(f"{BRAND_NAME} is running...")
    app.run_polling()


if __name__ == "__main__":
    main()
